pipeline {
    agent {
        docker {
            image : 'node:20-alphine3.16'
            args : '-p 3000:3000'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}